### ISSUE TITLE
[Architecture] Create common base class for instrument classes (OOP-ify)

### ISSUE THREAD

**Issue by john-b-at-keysight** [morgan-at-keysight/pyarbtools#24]

**Comment by morgan-at-keysight** [comment]
Began architecting this feature and realized that it's not really worth the effort. 

- The common methods used by all generators are different enough that they must be rewritten anyway.
- There are few enough common class attributes between the generators that the constructors of all the classes must be rewritten anyway.
- The classes all use the socketscpi.SocketInstrument base class to begin with.
