### ISSUE TITLE
timeout when connecting M8195A in a M9502A chassis

### ISSUE THREAD

**Issue by prettypoly** [morgan-at-keysight/pyarbtools#35]
Hi Morgan,

First, thank you so much for your effort to this repo. It could really facilitate our lab works.

I tried to use it to connect our M8195A (in a M9502A chassis). 
I can connect to the chassis with my PC (as a dhcp server) through ethernet. Keysight IO could identify the chassis and *IDN? returned ID of M9502A. The IP address of M9502A is 192.168.0.1.
![image](https://user-images.githubusercontent.com/45487765/109986651-3b1d8c00-7d06-11eb-95b8-3b09251d09d0.png)

The M950x SFP could also find the chassis. And it could even read the DAC temp and etc.
![image](https://user-images.githubusercontent.com/45487765/109986903-761fbf80-7d06-11eb-82ce-88a8bad50283.png)

However, I could not connect to the M8195A module in the chassis. The python script is not working. Both the script and the GUI complain "timeout".
![image](https://user-images.githubusercontent.com/45487765/109986733-4ec8f280-7d06-11eb-8a55-36b960a2c72b.png)

I also tired to open Keysight M8195 Soft Front Panel, but it could not find any instrument.
![image](https://user-images.githubusercontent.com/45487765/109986764-57b9c400-7d06-11eb-85b1-d7c9fa00409a.png)

When I connect the usb cable to the chassis, the M8195 SFP could find the instrument but pyarbtools still returns a timeout.

I think there must be something I missed, as this seems a problem of getting a connection to the module itself, not the chassis.
Is there a way to connect? Did I do anything wrong here?

Many thanks!

**Comment by morgan-at-keysight** [comment]
Happy to help! I hope you will find this tool to be useful.

There are a few things going on here that often cause confusion. 

The AXIe chassis itself _is not used_ for remote control. In other words, your program does not communicate with the chassis directly to send SCPI commands. The chassis only exists to provide power and connectivity for the modules inside it.

The M8195A soft front panel must be started prior to connecting to the AWG with PyArbTools (or any other SCPI-based control software). _This_ is the thing you're communicating with. 

When you use an AXIe chassis _without an embedded controller inside it_, you **must** have a connection between the controlling computer (presumably the one running PyArbTools) and the AXIe chassis. Often the easiest connection is USB, which you mentioned in your post. So in your case, connect a USB cable between your PC and the chassis.

Once you have the chassis and your PC connected via USB and have the M8195A soft front panel running and connected to the AWG, you can open up Keysight Connection Expert to verify what IP address should be used for connection. I believe in your case it will be `localhost`, or `127.0.0.1`.

So once all that is done, it should look something like this in the PyArbTools GUI:
![image](https://user-images.githubusercontent.com/39631985/110005143-050fe600-7ccd-11eb-92c3-298f54f0abd9.png)

**Comment by prettypoly** [comment]
Hi Morgan,

Thanks a lot for explaining how this is supposed to work. ;-)
I'll give it a try tomorrow at work and leave any feedback here. 

We used to have a Matlab-based library for this kind of work but we are moving to Python due to new projects that require Python preprocessing a lot of data. Therefore, I'm very grateful to see your work here. 

Best

**Comment by prettypoly** [comment]
Hi Morgan,

I just tried it out today and it worked like a charm! 
Thanks a lot for the help. 

Cheers,
