### ISSUE TITLE
Markers in download_wfm

### ISSUE THREAD

**Issue by stesteve** [morgan-at-keysight/pyarbtools#40]
This is my first experience with GitHub, and I am not yet confident to make any code contributions, but here are some things that look wrong to me in the download_wfm function for the M8190A:
1. The markerData variable is defined as an array of zeroes, then modified to add the marker, but then never used for anything.  Shouldn't the lines "i += sampleMkr" and "q += syncMkr" be "i += markerData" and "q += markerData" instead?
2. Shouldn't markerData be 1 for the sample marker and 2 for the sync marker?  They are both set to 1.  (Actually this would only be true for 'real' data; they would both be 1 for 'iq' data I think.)
3. sampleMkr and syncMkr are index values for the wfmData array, and 0 should be a valid index for a marker, but the lines "if sampleMkr:" and "if syncMkr:" cause the marker code to be skipped if the marker value is 0.

**Comment by mhejda** [comment]
Glad you brought this up, as I was facing issues with sample markers not working for me (in 'real' mode) and could not figure out what was wrong. I am also using M8190A.

I believe all of your points are valid. markerData is defined but never really used in the current version. Also, sample/sync markers seem to only be defined for 'iq' mode - in 'real' mode, markers are not handled at all.

The functionality of working markers in 'real' mode is the only thing I am missing before I can use this package for my experiments. I have a feeling the fix will not be complicated, but have not yet managed to find out how to do it (even when consulting Keysights SCPI manual). Any insights here would be very welcome.

**Comment by stesteve** [comment]
mhejda, I didn't notice that before about markers with 'real' data, but the word format shown in sections 8.22.4 and 8.22.5 of the M8190A user manual show that bits are used for markers in both real and iq modes.  Therefore the fact that the download_wfm function does not include markers with 'real' data should be raised as another issue.

**Comment by morgan-at-keysight** [comment]
Thank you both for bringing this up. I will investigate the marker functionality in the M8190 in both modes and see what's going on. 

This week is busy for me, but I will track down an M8190 and see what I can find.

**Comment by morgan-at-keysight** [comment]
Fixed the original marker issue and added marker functionality to the 'real' waveform type as well. Please upgrade to pyarbtools version 2021.06.2 using `pip install --upgrade pyarbtools`
