### ISSUE TITLE
Cannot run GUI

### ISSUE THREAD

**Issue by AndresChoza** [morgan-at-keysight/pyarbtools#49]
Hi, I just installed pyarbtools using pip and tried to run the GUI to try it out, the thing is that I'm getting this error:

> Traceback (most recent call last):
  File "/home/choza/Documents/workspace_py/pyarb.py", line 8, in <module>
    main()
  File "/home/choza/Documents/workspace_py/pyarb.py", line 5, in main
    pyarbtools.gui.main()
  File "/home/choza/.local/lib/python3.8/site-packages/pyarbtools/gui.py", line 1394, in main
    root.iconbitmap(iconPath)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/choza/.local/lib/python3.8/site-packages/pyarbtools/favicon.ico" not defined

Then I tried to manually download and place "favicon.ico" in the pyarbtools folder but I keep getting the same error...

**Comment by morgan-at-keysight** [comment]
Thanks for pointing this out. This is related to an icon that's used in the GUI's window bar. It's been a while since I've updated the GUI and I will take a look.

**Comment by morgan-at-keysight** [comment]
@AndresChoza I've included a fix for the GUI in the latest version (2022.4.1). Just tested it myself by cloning a fresh repository and running `example.py` with the `gui_example()` function.
