### ISSUE TITLE
Can't connect with socket

### ISSUE THREAD

**Issue by SBresler** [morgan-at-keysight/pyarbtools#54]
I am trying to use this package to connect to a M8190A that is in a M9505A chassis with a M9537A controller.

when I use pyvisa or NI MAX, I can connect with both the socket and vxi11 interface and an idn? query works fine.

but with pyarbtools, the connection doesn't complete OR timeout. If I put in the wrong IP, the connection does time out.

Any ideas?

**Comment by morgan-at-keysight** [comment]
The M8190A firmware should be running on the AXIe chassis. What socket port is shown in the M8190A firmware window? If it's 5025 (the default), it should work with no issues. If it's a different port number, you'll have to specify that port when creating the M8190A object in pyarbtools.

`weirdPort = 5026`
`awg = pyarbtools.instruments.M8190A(host, port=weirdPort)`

![image](https://user-images.githubusercontent.com/39631985/217955645-69d45d4f-8f32-4949-bb55-dd63bff80267.png)

**Comment by SBresler** [comment]
Hi, I think I have resolved this issue. I essentially modified the backend to let me refer to the computer name, and used the vxi11 interface through pyvisa - honestly all of my other stuff uses vxi11 so I'm happier with it. 

I am still having some trouble with stale certificates and it being a little bit unclear as to how I can update this thing without connecting to the internet, but that's beside the point for the moment since I can play things out on the arb which is 99% of what I want.

I do have some questions about... how to make a waveform that makes sense given some of the constraints on these devices. Do you know anyone who is knowledgeable about this?

An example is that I want to play out a 10 Mhz to 4.950 GHz chirp, and I want that chirp to repeat at 10 Mhz rate and constantly be playing. I often get complaints that the signal is not a multiple of 64 or something like that.

So my question is, how do I get the waveform that I want to loop over and over again while also ensuring that these other conditions are met? Is there a common technique for problems like this?

The arb seems a little bit... overwhelming with all of its capabilities. Even talking to someone that really knows what they are doing for an hour or so would be really helpful.

My interpretation of the chirp example is that this would mean that I want a duration of 10e-7, a center frequency of 10 Mhz, a bandwidth of 4.940 GHz, and that also means that I need to run at 12-bit (I forget the string for that) instead of 15 bit to get my nyquist frequency above 5 GHz. 

Thanks!
