### ISSUE TITLE
Remove `from pyarbtools import gui` from __init__

### ISSUE THREAD

**Issue by ant0nisk** [morgan-at-keysight/pyarbtools#56]
When importing pyarbtools I get an error from Tkinter. 

```
import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

I do not need the GUI, which I think is true for many people.

I'd recommend removing the line `from pyarbtools import gui` from `__init__.py` and if someone needs to use the GUI, they can then explicitly import it.

Thanks for the library, it really helps getting up and running quickly!

**Comment by morgan-at-keysight** [comment]
tkinter should be included with Python by default, so it _shouldn't_ be an issue. Just to make sure, I've changed all the tkinter imports gui.py to  explicit so that the '_tkinter' module is not imported. This is addressed in the most recent PR. Use pyarbtools 2023.10.1.
