### ISSUE TITLE
Timeout not applied on all API types in `SignalGeneratorBase`

### ISSUE THREAD

**Issue by ant0nisk** [morgan-at-keysight/pyarbtools#57]
**Issue**
The timeout parameter is not applied on all API types in `SignalGeneratorBase`.

**Potential fix**
I manually fixed it by placing `self.instance.timeout = timeout * 1000` (seconds to ms conversion). I am not sure if this is the right thing to do yet (I'm new to the library).

Something similar has been done here after calling `open_resource`: https://github.com/tektronix/keithley/blob/f6d951974b876ac6114549f516a42aed126c0683/Instrument_Examples/General/Instrument_Communication_Resouces/instrcomms.py#L58

**Breaking changes:**
Because of the difference in units, this does break the consistency of `__getattr__` for the timeout property across different backends/API types.

**Why fix it in** `SignalGeneratorBase` **?**
The reason why this needs to be done in this layer and not on the user-level is that the reset after initializing (for example) an M8190A can fail, because resetting can take time and resolve into an exception.

I'm using a M8190A with the hislip protocol and the PyVISA backend.

**Comment by morgan-at-keysight** [comment]
This is addressed in the most recent PR. Use pyarbtools 2023.10.1.
