### ISSUE TITLE
[Feature Request] PXI connection

### ISSUE THREAD

**Issue by qcl-sydney** [morgan-at-keysight/pyarbtools#9]
Adding the capability for connecting via PXI interface (currently only TCP/IP) will be great as it will speed up communication speed.

**Comment by morgan-at-keysight** [comment]
Thanks for submitting! Can you give some background for this request (e.g. which PXIe signal generators you had in mind)?

The PXIe-based vector signal generators supported by PyArbTools can use socket connections, which are about as fast as you can go without having PCIe interface cards between your computer and PXIe chassis.

**Comment by qcl-sydney** [comment]
I am communicating with a M8190 using PCIe interface card in my PC to take advantage of the speed. I am not able to connect to it via pyarbtool.

**Comment by jeff922** [comment]
I would expect PyArbTools to be able to work with an M8190A when using an external computer with PCIe interface card.  In this case, the M8190A software would need to run on the external pc.  Once it is running, the M8190A splash screen will display a VISA address.  If PyArbTools is running on the same pc, the ip address in PyArbTools would be localhost or 127.0.0.1.

Jeff



![M8190AStartScreen](https://user-images.githubusercontent.com/64092134/81945486-2aabf180-95cc-11ea-9e09-b1d8fbe6071b.png)

**Comment by morgan-at-keysight** [comment]
@qcl-sydney can you try @jeff-at-keysight 's suggestion? 

I can say right now that adding direct PXIe control is outside the scope of this project, which is SCPI-based.

**Comment by morgan-at-keysight** [comment]
Closing this issue  due to no response for 2 weeks.
